version: '3.8'

services:
  # PlayPulse Panel Application
  app:
    build: .
    container_name: playpulse-panel
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=playpulse
      - DB_USERNAME=playpulse
      - DB_PASSWORD=secure_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    depends_on:
      - database
      - redis
    networks:
      - playpulse

  # MySQL Database
  database:
    image: mysql:8.0
    container_name: playpulse-database
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: playpulse
      MYSQL_USER: playpulse
      MYSQL_PASSWORD: secure_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - database_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - playpulse

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: playpulse-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - playpulse

  # Queue Worker
  queue:
    build: .
    container_name: playpulse-queue
    restart: unless-stopped
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=playpulse
      - DB_USERNAME=playpulse
      - DB_PASSWORD=secure_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./storage:/var/www/html/storage
    depends_on:
      - database
      - redis
    networks:
      - playpulse

  # Scheduler
  scheduler:
    build: .
    container_name: playpulse-scheduler
    restart: unless-stopped
    command: php artisan schedule:work
    environment:
      - APP_ENV=production
      - DB_CONNECTION=mysql
      - DB_HOST=database
      - DB_PORT=3306
      - DB_DATABASE=playpulse
      - DB_USERNAME=playpulse
      - DB_PASSWORD=secure_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./storage:/var/www/html/storage
    depends_on:
      - database
      - redis
    networks:
      - playpulse

volumes:
  database_data:
    driver: local
  redis_data:
    driver: local

networks:
  playpulse:
    driver: bridge